name       : libvdpau-va-gl
version    : 0.4.2
release    : 4
source     :
    - https://github.com/i-rinat/libvdpau-va-gl/releases/download/v0.4.2/libvdpau-va-gl-0.4.2.tar.gz : 7d9121540658eb0244859e63da171ca3869e784afbeaf202f44471275c784af4
license    : LGPL-3.0
summary    : VDPAU driver with OpenGL/VAAPI backend
component  : xorg.display
description: |
    VDPAU driver with OpenGL/VAAPI backend
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(vdpau)
    - pkgconfig(libva-x11)
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
