name       : libvdpau-va-gl
version    : 0.3.4
release    : 1
source     :
    - https://github.com/i-rinat/libvdpau-va-gl/releases/download/v0.3.4/libvdpau-va-gl-0.3.4.tar.gz : 5506896d11fcf5d4537d0b9a6cb7404da9b26796f6445913779617fbd85d550b
license    : LGPL-3.0
summary    : VDPAU driver with OpenGL/VAAPI backend
description: |
    VDPAU driver with OpenGL/VAAPI backend
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(vdpau)
    - pkgconfig(libswscale)
    - pkgconfig(libva-x11)
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
